version: "3.7"
services:
  screeps:
    container_name: screeps
    image: qnimbus/docker-screeps
    build: ./
    networks:
      - screeps
    volumes:
      - /opt/screeps:/screeps
    ports:
      - 21025:21025
      - 21026:21026
    environment:
      - STEAM_KEY=
      - LOCAL_UID=1101
      - GAME_PORT=21025
      - CLI_PORT=21026
    restart: "no"
    depends_on:
      - mongo
      - redis
  mongo:
    container_name: mongo
    image: mongo
    networks:
      - screeps
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    restart: "no"
  redis:
    container_name: redis
    image: redis
    networks:
      - screeps
    volumes:
      - redis-data:/data
    restart: "no"

volumes:
  mongo-data:
  mongo-config:
  redis-data:

networks:
  screeps:
    name: screeps_net
    driver: bridge
